language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
  - "iojs"
install:
  - npm install
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8




