language: node_js
dist: bionic
node_js:
  - "14.8"
  - "12.18"
install:
  - npm install
    npm install --no-save wson-addon
env:
  - CXX=g++-7
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

